/**
 *
 *  Produtseller.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Produtseller.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string Produtseller::primaryKeyName = "";
const bool Produtseller::hasPrimaryKey = false;
const std::string Produtseller::tableName = "\"produtSeller\"";

const std::vector<typename Produtseller::MetaData> Produtseller::metaData_={
};
const std::string &Produtseller::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Produtseller::Produtseller(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Produtseller::Produtseller(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Produtseller::Produtseller(const Json::Value &pJson) noexcept(false)
{
}

void Produtseller::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Produtseller::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Produtseller::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Produtseller::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Produtseller::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Produtseller::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Produtseller::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Produtseller::toJson() const
{
    Json::Value ret;
    return ret;
}

std::string Produtseller::toString() const
{
    return toJson().toStyledString();
}

Json::Value Produtseller::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Produtseller::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Produtseller::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Produtseller::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Produtseller::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Produtseller::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
